services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./jteam:/jteam
      - media_data:/jteam/media
      - ./entrypoint.sh:/entrypoint.sh
    env_file:
      - .env
    environment:
      - DB_HOST=${POSTGRES_DB_HOST}
      - DB_NAME=${POSTGRES_DB_NAME}
      - DB_USER=${POSTGRES_DB_USER}
      - DB_PASS=${POSTGRES_DB_PASSWORD}
    command: sh /entrypoint.sh
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always
    networks:
      - vsporte

  database:
    image: postgres:14.6-alpine
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    networks:
      - vsporte
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_DB_USER} -d ${POSTGRES_DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.0.5-alpine
    hostname: redis
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - vsporte
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  worker:
    build:
      context: .
    hostname: worker
    restart: always
    entrypoint: celery
    command: -A jteam.celery:app worker --loglevel=info
    volumes:
      - ./jteam:/jteam
      - media_data:/jteam/media
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DB_HOST=${POSTGRES_DB_HOST}
      - DB_NAME=${POSTGRES_DB_NAME}
      - DB_USER=${POSTGRES_DB_USER}
      - DB_PASS=${POSTGRES_DB_PASSWORD}
    networks:
      - vsporte

  celery-beat:
    build:
      context: .
    restart: always
    entrypoint: celery
    command: [ "-A", "jteam.celery:app", "beat", "--loglevel=info" ]
    volumes:
      - ./jteam:/jteam
      - media_data:/jteam/media
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DB_HOST=${POSTGRES_DB_HOST}
      - DB_NAME=${POSTGRES_DB_NAME}
      - DB_USER=${POSTGRES_DB_USER}
      - DB_PASS=${POSTGRES_DB_PASSWORD}
    networks:
      - vsporte

#  flower:
#    build:
#      context: .
#    hostname: flower
#    entrypoint: celery
#    command: -A jteam.celery:app flower
#    volumes:
#      - ./jteam:/jteam
#    links:
#      - redis
#    depends_on:
#      - redis
#    ports:
#      - "5555:5555"
#    networks:
#      - vsporte

#  pgadmin:
#    image: dpage/pgadmin4
#    container_name: jteam_pgadmin
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
#      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
#      - PGADMIN_LISTEN_PORT=80
#    ports:
#      - "8080:80"
#    depends_on:
#      - database
#    networks:
#      - vsporte

networks:
  vsporte:


volumes:
  postgres_data:
  redis_data:
  media_data:
