# Generated by Django 4.2.11 on 2024-05-25 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
            ],
            options={
                "verbose_name": "city",
                "verbose_name_plural": "cities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="places/%Y/%m/%d")),
                ("price", models.DecimalField(decimal_places=0, max_digits=10)),
                ("available", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="places",
                        to="location.city",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddIndex(
            model_name="city",
            index=models.Index(fields=["name"], name="location_ci_name_673b17_idx"),
        ),
        migrations.AddIndex(
            model_name="place",
            index=models.Index(fields=["id", "slug"], name="location_pl_id_a3671e_idx"),
        ),
        migrations.AddIndex(
            model_name="place",
            index=models.Index(fields=["name"], name="location_pl_name_fce7cc_idx"),
        ),
        migrations.AddIndex(
            model_name="place",
            index=models.Index(
                fields=["-created"], name="location_pl_created_b17064_idx"
            ),
        ),
    ]
