# Generated by Django 5.2.3 on 2026-06-24 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('friendship_request', 'Заявка в друзья'), ('friendship_accepted', 'Заявка в друзья принята'), ('game_participation_request', 'Заявка на участие в игре'), ('game_invitation', 'Приглашение на игру'), ('game_participation_accepted', 'Заявка на участие принята'), ('game_participation_rejected', 'Заявка на участие отклонена')], max_length=50)),
                ('target_id', models.PositiveIntegerField()),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_sent', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('target_ct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_targets', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['recipient', '-created'], name='notificatio_recipie_56ba46_idx'), models.Index(fields=['recipient', 'read_at'], name='notificatio_recipie_564b1f_idx')],
            },
        ),
    ]
