# Generated by Django 4.2.11 on 2026-08-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('friendship_request', 'Заявка в друзья'), ('friendship_accepted', 'Заявка в друзья принята'), ('game_participation_request', 'Заявка на участие в игре'), ('game_invitation', 'Приглашение на игру'), ('game_participation_accepted', 'Заявка на участие принята'), ('game_participation_rejected', 'Заявка на участие отклонена'), ('game_player_removed', 'Исключение из мероприятия'), ('chat_message', 'Сообщение в чате игры'), ('game_updated', 'Изменение условий игры'), ('group_join_request', 'Заявка на вступление в группу'), ('group_invitation', 'Приглашение в группу'), ('group_join_accepted', 'Заявка на вступление принята'), ('group_join_rejected', 'Заявка на вступление отклонена'), ('group_member_removed', 'Исключение из группы')], max_length=50),
        ),
    ]
