# Generated by Django 4.2.11 on 2025-03-11 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[('football', 'футбол'), ('tennis', 'теннис'), ('bowling', 'боулинг'), ('beach volleyball', 'пляжный волейбол'), ('volleyball', 'волейбол'), ('ice hockey', 'хоккей на льду'), ('chess', 'шахматы')], max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.DurationField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_players', models.PositiveIntegerField(default=2)),
                ('status', models.CharField(choices=[('open', 'Open'), ('started', 'Started'), ('finished', 'Finished')], default='Open', max_length=255)),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='images/%Y/%m/%d')),
                ('joined_players', models.ManyToManyField(blank=True, related_name='joined_games', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_games_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['created_at'], name='games_game_created_1f2afd_idx')],
            },
        ),
    ]
