# Generated by Django 4.2.11 on 2025-03-12 21:42

import datetime
from django.db import migrations, models
import django.utils.timezone
import games.models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600), help_text='Продолжительность игры (чч:мм)'),
        ),
        migrations.AlterField(
            model_name='game',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, validators=[games.models.validate_future_datetime]),
        ),
    ]
