# Generated by Django 4.2.11 on 2025-03-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_game_duration_alter_game_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('started', 'Started'), ('finished', 'Finished')], default='open', max_length=255),
        ),
    ]
