# Generated by Django 5.2.3 on 2026-06-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_sync_game_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='has_skill_level',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='place_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
