# Generated by Django 5.2.3 on 2026-06-25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0006_game_has_skill_level_game_place_reserved"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameParticipationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participation_requests",
                        to="games.game",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_participation_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.AddIndex(
            model_name="gameparticipationrequest",
            index=models.Index(
                fields=["game", "status"], name="games_gamepa_game_id_8f0fd1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gameparticipationrequest",
            index=models.Index(
                fields=["-created"], name="games_gamepa_created_6b2f0a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="gameparticipationrequest",
            constraint=models.UniqueConstraint(
                fields=("game", "user"),
                name="unique_game_participation_request",
            ),
        ),
    ]
