# Generated by Django 5.2.3 on 2026-07-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0009_gamemessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="extra_players",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Доп. участники, которых организатор приводит офлайн",
            ),
        ),
    ]
