# Generated by Django 5.2.3 on 2026-07-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0010_game_extra_players"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="skill_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("beginner", "Начинающий"),
                    ("intermediate", "Средний"),
                    ("advanced", "Продвинутый"),
                    ("pro", "Профи"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
