# Generated by Django 4.2.11 on 2026-08-09 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("games", "0011_game_skill_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="is_team_game",
            field=models.BooleanField(
                default=False,
                help_text="Командная игра: составы A/B поверх общего пула участников",
            ),
        ),
        migrations.CreateModel(
            name="GameTeamAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "team",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Команда A"), (2, "Команда B")]
                    ),
                ),
                (
                    "offline_slot",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_assignments",
                        to="games.game",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_team_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Назначение в команду",
                "verbose_name_plural": "Назначения в команды",
            },
        ),
        migrations.AddIndex(
            model_name="gameteamassignment",
            index=models.Index(
                fields=["game", "team"], name="games_gamet_game_id_21db81_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="gameteamassignment",
            constraint=models.CheckConstraint(
                check=models.Q(("team__in", [1, 2])),
                name="game_team_assignment_team_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="gameteamassignment",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("offline_slot__isnull", True), ("user__isnull", False)
                    ),
                    models.Q(
                        ("offline_slot__isnull", False), ("user__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="game_team_assignment_user_xor_offline",
            ),
        ),
        migrations.AddConstraint(
            model_name="gameteamassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("game", "user"),
                name="unique_game_team_assignment_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="gameteamassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("offline_slot__isnull", False)),
                fields=("game", "offline_slot"),
                name="unique_game_team_assignment_offline",
            ),
        ),
    ]
