# Generated by Django 4.2.11 on 2026-08-10 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('sport', models.CharField(choices=[('football', 'футбол'), ('tennis', 'теннис'), ('bowling', 'боулинг'), ('beach volleyball', 'пляжный волейбол'), ('volleyball', 'волейбол'), ('ice hockey', 'хоккей на льду'), ('chess', 'шахматы')], max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='images/%Y/%m/%d')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(blank=True, related_name='joined_communities', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_communities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='groups.community')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_invitations_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='CommunityJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='groups.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['community', 'status'], name='groups_comm_communi_2c7efe_idx'), models.Index(fields=['-created'], name='groups_comm_created_7fbd36_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='communityjoinrequest',
            constraint=models.UniqueConstraint(fields=('community', 'user'), name='unique_community_join_request'),
        ),
        migrations.AddIndex(
            model_name='communityinvitation',
            index=models.Index(fields=['community', 'status'], name='groups_comm_communi_45591c_idx'),
        ),
        migrations.AddIndex(
            model_name='communityinvitation',
            index=models.Index(fields=['-created'], name='groups_comm_created_d6407b_idx'),
        ),
        migrations.AddConstraint(
            model_name='communityinvitation',
            constraint=models.UniqueConstraint(fields=('community', 'to_user'), name='unique_community_invitation'),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['-created_at'], name='groups_comm_created_20ae62_idx'),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['sport'], name='groups_comm_sport_26fbcb_idx'),
        ),
    ]
