# Generated by Django 4.2.11 on 2026-07-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_profile_show_email_interests'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='friendship',
            new_name='account_fri_created_fc837a_idx',
            old_name='account_fri_created_6e0f0d_idx',
        ),
        migrations.AddField(
            model_name='profile',
            name='location_address',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='profile',
            name='location_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='recent_locations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
