# Generated by Django 4.2.11 on 2026-08-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_profile_phone_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneverification',
            name='purpose',
            field=models.CharField(choices=[('register', 'Регистрация'), ('change', 'Смена телефона'), ('login', 'Вход')], default='register', max_length=20),
        ),
    ]
